
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imx1a2V3IiwiaWQiOiI2NzRiNGM4NzUzOGRmZDEzNmRhYTc4ZTMiLCJpYXQiOjE3MzI5ODgxODh9.FGRX2ysUvXQMzTYYsY3uvrIrXYpRxcq4cLaGGOkDWaI

{
        "title": "TestTest",
        "author": "Author",
        "url": "http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html",
        "likes": "5"
        
}