DELETE http://localhost:3003/api/blogs/6701951c7e1b1b839b3f15e2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbGxhcyIsImlkIjoiNjcwMTU0NDkxMGM4Yzk0ZTI5NTlkNmE0IiwiaWF0IjoxNzI4MTU2MDA4fQ.735-DQM099Ma3zOR9HVkVGJSWGfrhqPpjbL7mGRYuZA

